# Generated by Django 2.2.7 on 2019-11-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191128_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', help_text='Age', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='primary_flur_color',
            field=models.CharField(choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='Grey', help_text='Primary flur color', max_length=30),
        ),
    ]
